name: ReleaseManager Production
description: Automate production releases with versioning. Streamline deployments for efficient and controlled updates.

branding:
  icon: 'git-merge'
  color: 'gray-dark'

inputs:
  production_branch:
    description: 'The name of the production branch'
    required: true
  github_token:
    description: 'GitHub token for accessing repository'
    required: true
  heroku_api_key:
    description: 'API key for accessing Heroku'
    required: true
  heroku_app_name:
    description: 'Name of the Heroku app'
    required: true
  slack_api_token:
    description: 'API token for accessing Slack'
    required: true
  slack_channel_id:
    description: 'ID of the Slack channel'
    required: true
  display_name:
    description: 'Display name for Slack messages'
    required: true
  pat:
    description: 'Personal access token for GitHub'
    required: true
  pull_request_head_ref:
    description: 'Pull Request head ref'
    required: true
  actor:
    description: 'Github actor'
    required: true
  pull_request_base_sha:
    description: 'Pull Request base sha'
    required: true
  pull_request_current_sha:
    description: 'Pull Request current sha'
    required: true

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  after_daily_deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == github.event.inputs.production_branch
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Production Branch
      uses: actions/checkout@v4
      with:
        ref: github.event.inputs.production_branch
        fetch-depth: 0
        token: github.event.inputs.pat

    - name: Set Variables
      id: set-variables
      env:
        GH_TOKEN: github.event.inputs.github_token
      run: |
        daily_deploy=false
        if [[ "${{ inputs.pull_request_head_ref }}" == "dev" ]]; then
          daily_deploy=true
        fi

        LATEST_TAG=$(gh release view --json tagName -q .tagName)

        major=$(echo $LATEST_TAG | cut -d. -f1)
        minor=$(echo $LATEST_TAG | cut -d. -f2)
        patch=$(echo $LATEST_TAG | cut -d. -f3)

        if $daily_deploy; then
          ((minor=minor+1))
          patch=0
        else
          ((patch=patch+1))
        fi

        RELEASE_TAG="$major.$minor.$patch"

        ((minor=minor+1))

        NEXT_RELEASE_TAG="$major.$minor.0"

        echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_OUTPUT"
        echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
        echo "NEXT_RELEASE_TAG=$NEXT_RELEASE_TAG" >> "$GITHUB_OUTPUT"

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: github.event.inputs.heroku_api_key
        heroku_app_name: github.event.inputs.heroku_app_name
        heroku_email: '${{ inputs.actor }}@users.noreply.github.com'

    - name: Create Release Tag
      env:
        GH_TOKEN: github.event.inputs.github_token
        LATEST_TAG: ${{ steps.set-variables.outputs.LATEST_TAG }}
        RELEASE_TAG: ${{ steps.set-variables.outputs.RELEASE_TAG }}
      run: |
        COMMITS=$(git log --pretty=format:'- %s' ${{ inputs.pull_request_base_sha}}..${{ inputs.current_sha }} --no-merges --reverse)
        BODY=$(printf "%s\n\nFull Changelog: %s" "$COMMITS" "[$LATEST_TAG...$RELEASE_TAG](https://github.com/LeCollectionist/${{ env.GITHUB_REPOSITORY }}/compare/$LATEST_TAG...$RELEASE_TAG)")
        gh release create $RELEASE_TAG --target ${{ inputs.production_branch }} --notes "$BODY" --title $RELEASE_TAG

    - name: Send message to Slack
      env:
        SLACK_API_TOKEN: github.event.inputs.slack_api_token
        SLACK_CHANNEL_ID: github.event.inputs.slack_channel_id
        RELEASE_TAG: ${{ steps.set-variables.outputs.RELEASE_TAG }}
        DISPLAY_NAME: github.event.inputs.display_name
      run: |
        COMMITS=$(git log --pretty=format:'- %s' ${{ inputs.pull_request_base_sha}}..${{ inputs.current_sha }} --no-merges --reverse)
        PAYLOAD='{"text":"<!here> Deploy `$DISPLAY_NAME` - Version '$RELEASE_TAG'\n```'"$COMMITS"'```", "channel":"'"$SLACK_CHANNEL_ID"'"}'
        curl -X POST -H "Content-type: application/json" -H "Authorization: Bearer $SLACK_API_TOKEN" --data "$PAYLOAD" "https://slack.com/api/chat.postMessage"

    - name: Checkout Dev
      uses: actions/checkout@v4
      with:
        ref: dev
        fetch-depth: 0
        token: github.event.inputs.pat

    - name: Rebase Production Branch into Dev
      if: github.event.pull_request.head.ref != 'dev'
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

        git rebase origin/${{ inputs.production_branch }}

        if [ $? -eq 0 ] && [ -z "$(git diff origin/dev)" ]; then
          git push -f origin dev
        fi

    - name: Update Version Configuration on Dev
      if: github.event.pull_request.head.ref == 'dev'
      env:
        NEXT_RELEASE_TAG: ${{ steps.set-variables.outputs.NEXT_RELEASE_TAG }}
      run: |
        sed -i "s/config.app_version = \"[^\"]*\"/config.app_version = \"$NEXT_RELEASE_TAG\"/" ./config/initializers/bugsnag.rb

        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

        git add ./config/initializers/bugsnag.rb
        git commit -m "chore(app-version): Bump app version to $NEXT_RELEASE_TAG"
        git push origin dev

    - name: Create Daily Pull Request
      if: github.event.pull_request.head.ref == 'dev'
      env:
        GH_TOKEN: github.event.inputs.github_token
      run: |
        gh pr create --base ${{ inputs.production_branch }} --head dev --title "${{ inputs.production_branch }} < Dev" --body "$(cat .github/PULL_REQUEST_TEMPLATE/TEMPLATE_FOR_PRODUCTION.md)"
